kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: idp
  namespace: {{ .Values.namespace }}
spec:
  host: "backstage-{{ .Values.namespace }}.{{ .Values.route.domain }}"
  to:
    kind: Service
    name: helm-backstage
    weight: 100
  port:
    targetPort: http-backend
  tls:
    termination: edge
  wildcardPolicy: None
