apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: backstage-token-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: "my-backstage"